@BAIPetRegMobileApp.Api_HostAddress = https://localhost:7107

GET {{BAIPetRegMobileApp.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{BAIPetRegMobileApp.Api_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "John Mark Pulmano",
  "email": "johnmarkpulmano@gmail.com",
  "password": "123"
}

###
